// <auto-generated />
using System;
using BinhDinhFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BinhDinhFood.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241022172426_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("ApplicationUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe744598-20f7-4d11-bc3e-968f00dff0b6"),
                            AccessFailedCount = 0,
                            Address = "Quy Nhơn, Bình Định",
                            ConcurrencyStamp = "c8f6c8dd-24eb-4a02-b142-30677eafa097",
                            Email = "truongnhon@example.com",
                            EmailConfirmed = false,
                            ImageId = 51,
                            LockoutEnabled = false,
                            Name = "Võ Thương Trường Nhơn",
                            PasswordHash = "AQAAAAIAAYagAAAAEKrx6RRi/XbeKEU6vO85LxbjmNEBDIp1kkAMr72zazuqF3ZuiCA/zcdOLAGDc7FmsA==",
                            PhoneNumber = "0905726748",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f4205e6-2f8f-4cbd-8b0c-a688867e7018",
                            TwoFactorEnabled = false,
                            UserName = "truongnhon"
                        },
                        new
                        {
                            Id = new Guid("bad8eb9e-05ed-4040-9494-ca5de7498094"),
                            AccessFailedCount = 0,
                            Address = "Tây Ninh",
                            ConcurrencyStamp = "0fcd717a-fcf3-4c12-b78c-df235590cd86",
                            Email = "hongthai@example.com",
                            EmailConfirmed = false,
                            ImageId = 52,
                            LockoutEnabled = false,
                            Name = "Nguyễn Hồng Thái",
                            PasswordHash = "AQAAAAIAAYagAAAAEH6x+TZPUo0cVQgl49TNOu4sWv7kfz5ih9uO8GUhz4tujWW67QsCSUDq3e8zauQRnw==",
                            PhoneNumber = "0905726748",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5fd2f35a-f03c-457b-8959-3f089d211b19",
                            TwoFactorEnabled = false,
                            UserName = "thai"
                        },
                        new
                        {
                            Id = new Guid("bc7fac01-c39e-4512-ada7-f03f09d5194f"),
                            AccessFailedCount = 0,
                            Address = "Nam Định",
                            ConcurrencyStamp = "0b740a46-a7f1-4fd8-9d46-51587c9abd47",
                            Email = "taiphamduc@example.com",
                            EmailConfirmed = false,
                            ImageId = 53,
                            LockoutEnabled = false,
                            Name = "Phạm Đức Tài",
                            PasswordHash = "AQAAAAIAAYagAAAAEPbQoP7CbydgTXUtKl/LndbBSQFYyx061fXj3GGFF6WGifKw7PBNAIr9e3LDDsR9xQ==",
                            PhoneNumber = "0905726748",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "342e1407-a5db-4907-abb9-7f7387dabeac",
                            TwoFactorEnabled = false,
                            UserName = "tai"
                        },
                        new
                        {
                            Id = new Guid("4d60f144-c346-42cc-952c-efcc255d06cf"),
                            AccessFailedCount = 0,
                            Address = "Saigon",
                            ConcurrencyStamp = "9090ca4a-bc8d-4767-94e0-e0bb59efc5fb",
                            Email = "nhondeptrai@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "dotnet evil",
                            PasswordHash = "AQAAAAIAAYagAAAAEDpeR5+1vWQkzmQN8Vif4RFPHKJ8oS8XfIXX37mS2IG1gBJ9HjqABPLZB8fOQUhC8w==",
                            PhoneNumber = "0905726748",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8782c658-b8f2-47c6-afa8-8952fb332e91",
                            TwoFactorEnabled = false,
                            UserName = "nhondeptrai"
                        },
                        new
                        {
                            Id = new Guid("6e726b2e-144a-40d7-b66e-30ca64a6575e"),
                            AccessFailedCount = 0,
                            Address = "Admin City",
                            ConcurrencyStamp = "7888893d-a57b-4a36-be01-66dc654980fd",
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Admin User",
                            PasswordHash = "AQAAAAIAAYagAAAAEKFVwN9Zr0Vv3o0LKOYFiMdyqW2halKo0aczCCUV6dXwhdf6vTpVL9aXaQmgzxxQUw==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b61c8137-c82a-41de-b872-79ca5afdbd14",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.ForgotPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ForgotPassword", (string)null);
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.RoleIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3314be5-4c77-4fb6-82ad-302014682a73"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b4314be5-4c77-4fb6-82ad-302014682b13"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("6e726b2e-144a-40d7-b66e-30ca64a6575e"),
                            RoleId = new Guid("a3314be5-4c77-4fb6-82ad-302014682a73")
                        },
                        new
                        {
                            UserId = new Guid("fe744598-20f7-4d11-bc3e-968f00dff0b6"),
                            RoleId = new Guid("b4314be5-4c77-4fb6-82ad-302014682b13")
                        },
                        new
                        {
                            UserId = new Guid("bad8eb9e-05ed-4040-9494-ca5de7498094"),
                            RoleId = new Guid("b4314be5-4c77-4fb6-82ad-302014682b13")
                        },
                        new
                        {
                            UserId = new Guid("bc7fac01-c39e-4512-ada7-f03f09d5194f"),
                            RoleId = new Guid("b4314be5-4c77-4fb6-82ad-302014682b13")
                        },
                        new
                        {
                            UserId = new Guid("4d60f144-c346-42cc-952c-efcc255d06cf"),
                            RoleId = new Guid("b4314be5-4c77-4fb6-82ad-302014682b13")
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Banner", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chả cá Quy Nhơn nổi tiếng với hương vị đặc trưng, được làm từ cá tươi ngon vùng biển Quy Nhơn.",
                            Discount = 10,
                            Name = "Chả cá Quy Nhơn",
                            Price = 100000m
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gỏi cá chình là món ăn đặc sản với hương vị chua ngọt, kết hợp từ cá chình tươi ngon và các loại rau thơm.",
                            Discount = 15,
                            Name = "Gỏi cá Chình",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nem chợ Huyện, món ăn truyền thống với hương vị thơm ngon, được làm từ thịt heo tươi và gia vị đặc trưng.",
                            Discount = 5,
                            Name = "Nem chợ Huyện",
                            Price = 150000m
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Mực rim là món ăn phổ biến khiến du thích yêu thích có mặt ở hầu hết những vùng biển lớn. Tuy nhiên mực rim hay còn gọi là mực ngào Bình Định có một hương vị thơm ngon rất riêng từ vùng biển duyên hải miền Trung. Mực rim Quy Nhơn được người dân làm từ những con mực tươi nhất và hương vị không nơi nào giống được. Với hương thơm ngon đặc biệt cùng vị cay cay kích thích vị giác, mực rim trở thành món ăn vặt siêu ngon và được mọi người vô cùng yêu thích. Đồng thời, với những hũ mực rim được làm sẵn giúp bạn có thể dễ dàng lựa chọn đặc sản Bình Định này để làm quà tặng.",
                            DateCreated = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mực rim Quy Nhơn"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Với tên gọi độc và lạ của món Chả Tré, món đặc sản Bình Định này đã gợi nên sự tò mò với nhiều du khách muốn tìm hiểu và được thử món ăn độc đáo này. Mặc dù đã có mặt phổ biến khắp các tỉnh thành Trung Trung bộ, nhưng hương vị thơm ngon nhất vẫn là chả Tré Bình Định với cách làm và công thức chỉ vùng đất Bình Định mới làm nên được.Thành phần nguyên liệu làm chả Tré cũng tương tự với các loại nem, bì của miền bắc. Nhưng Tré Bình Định được người dân nơi đây khéo léo thay thế bằng nhiều loại nguyên liệu khác như tai heo, lỗ mũi heo, da heo, thịt ba chỉ,...Tré cũng thích hợp để trở thành món quà mang về khi bạn đến thăm Bình Định.",
                            DateCreated = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chả Tré rơm"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Mặc dù chả cá có thể là đặc sản và có mặt ở nhiều nơi nhưng không phải hương vị chả cá nào cũng như nhau. Sở dĩ chả cá Quy Nhơn là một trong các đặc sản Bình Định nổi tiếng vì vị ngon và lạ đặc trưng. Với nguyên liệu được tuyển chọn từ những con cá biển tươi ngon nhất và công thức chế biến độc quyền của người dân đã tạo nên sự khác biệt cho chả cá Quy Nhơn. Chả cá Quy Nhơn phổ biến có 2 loại là chả hấp và chả chiên. Ngoài việc thưởng thức thực tiếp miếng chả dai, giòn, thơm ngon đặc biệt, các bạn có thể dùng chả cá này để làm “topping” cho các món ăn khác như cơm, bún, phở. Đây cũng là một lựa chọn thích hợp để bạn mua về làm quà cho người thân và bạn bè nữa đó.",
                            DateCreated = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chả cá Quy Nhơn"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Đây là một món ngon đặc sản Quy Nhơn rất đỗi bình dị nhưng được du khách rất yêu thích. Nó được bày bán ở hầu hết các quán xá vỉa hè ở Bình Định. Bánh xèo được làm được những  nguyên liệu đơn giản như thịt heo băm nhuyễn, hành phi, rau thơm, trứng và bột gạo. Gaọ sẽ được tuyển chọn những những gạo to chắc mẩy không bị sâu để tạo độ ngọt của bánh. Gạo sẽ được đem đi xay và nấu bột thành một thứ hỗn hợp dẻo, đập trứng cho thịt băm và một số loại gia vị vào. Bên cạnh đó đac có một cái chảo đang được đun nóng. Người nấu sẽ múc từng múc lên chảo để tráng những miếng bánh, dải thịt băm nhuyễn đã được xào chín lên bên trên bề mặt bánh và guộn đều tay để bánh to tròn và đẹp. Hoặc có thể là những con tôm tươi ngon. Khi  ăn ăn kèm với rau thơm và nước chấm.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bánh Xèo Mỹ Cang"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Khi đến du lịch Bình Định không thể không nhắc tới  món bánh tráng nước dừa. Đây là một món đặc sản nơi xứ dừa. Công đoạn chế biến bánh không quá cầu kì nhưng đòi hỏi sự tỉ mỉ, có kinh nghiệm của người tráng bánh. Nguyên liệu của bánh chủ yếu là Củ Mì ( củ sắn) được sắt nhỏ, xay lấy nước. Cơm dừa được nạo thành sợi nhỏ,  nước dừa và vừng đen. Tất cả đều được đổ chung vào một nồi lớn, trộn đều cho các gia vị hòa quyện cùng với nhau và được đun nóng. Bên cạnh đó có một chảo đang được đun nóng. Khi chảo nóng lên người tráng bánh sẽ dùng một cái gáo làm bằng sọ dừa có cán dài múc từng gáo nước bánh lên chảo và tráng đều. Tráng bánh phải đều tay để cơm dừa và vừng đen được dàn đều mặt bánh. Bánh phải tròn mỏng và không bị chỗ dày, chỗ mỏng thì mới là bánh đạt chuẩn. cứ tráng được mười chiếc  bánh thì đem ra phơi. khi ăn bạn cần nướng lên để bánh có độ phồng và dậy hết mùi thơm của vừng, của nước cốt dừa và cơm dừa. Có thể ăn bánh thay cơm ăn chỉ thấy no mà không thấy chán.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bánh tráng nước dừa"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Bún song thần có chút khác biệt với các loại bún thông thường khác bởi thay vì sợi bún được làm từ bột gạo hay bột củ mì kéo sợi thì bún song thần lại được làm từ bột đậu xanh. Bún Song thần đặc sản Bình Định có màu trắng đặc trưng. Bún được đặt song  song bên nhau nên có tên là bún song thần. Món đặc sản này có giá trị dinh dưỡng cao hơn các loại bún khác. Tuy nhiên giá thành của bún khá cao bởi 5kg đậu xanh chỉ là được 1kg bún.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bún song  thần"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Món món hải sản ngon nức tiếng ở Bình Định. Cua Huỳnh đếđược xem là vua của các loại cua bởi nó có mai đỏ vàng như một bộ long bào uy nghi của các nhà vua, hai bên có gai li ti sắc nhọn, hai chiếc càng to chắc khỏe. Cua thường sống trong những ngách đá trên biển Bình Định. Cua Huỳnh Đế có thịt thơm, chắc  và có thể chế biến thành nhiều món ăn ngon khác nhau như cua nướng, cua hấp… đều rất thơm ngon.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cua Huỳnh Đế"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Cá Chích là loại cá nước ngọt sống ở các sông hồ ao suối. Cũng bởi Bình Định có nhiều sông hồ nên đây là môi trường thuận lợi để loài đặc sản này sinh sống. Cá Chích đặc sản Bình Định có thân  hình nhỏ, dài. Cá Chích sau khi được  đánh bắt lên sẽ được làm  sạch  và chiên giòn. Vì  là loài cá có kích cỡ nhỏ nên  khi ăn  người ta sẽ kẹp cả con cá đã được chiên vàng ăn với bánh phở cuốn, kèm rau thơm, dưa chuột. Cá ngọt thịt nên bạn ăn sẽ không bị chán. Tuy Nhiên nếu bạn là tín đồ gỏi sống bạn có thể được  thưởng thức gỏi cá chích với những thớ thịt  đc lọc xương làm sạch.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gỏi cá chích"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Bánh hồng Tam Quan là một trong những món đặc sản của Bình Định, được xem như biểu trưng cho tin vui, thường xuất hiện trong các dịp cưới hỏi của người dân nơi đây. Điều đặc biệt bánh hồng Tam Quan là bánh được làm từ gạo nếp Ngự nổi tiếng dẻo thơm. Do hoàn toàn không có chất bảo quản nên bánh chỉ để được 5 ngày thôi bạn nhé.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bánh hồng Tam Quan"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Bánh tráng chả cá là một trong những đặc sản nổi tiếng gần xa của Bình Định. Bánh tráng chả cá được làm từ nguyên liệu chính là cá cùng một ít gia vị và bột năng. Để món ăn đúng vị hơn bạn nên ăn kèm với rau răm nhé.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bánh tráng chả cá"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Nếu đã đến với đất Bình Định thì bạn nhất định phải thử qua món mực ngào vị tỏi nhé. Món ăn là sự hòa quyện giữa vị mực vừa tươi vừa giòn cùng vị cay đặc trưng của ớt và tỏi. Bạn nhớ bảo quản món này ở nhiệt độ thoáng mát nha.",
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mực ngào vị tỏi"
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A comprehensive guide to C# programming.",
                            Price = 29.989999999999998,
                            Title = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Learn how to build web applications using ASP.NET Core.",
                            Price = 35.5,
                            Title = "ASP.NET Core Development"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Master the Entity Framework Core ORM for .NET development.",
                            Price = 40.0,
                            Title = "Entity Framework Core In Action"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Everything you need to know about building Blazor WebAssembly applications.",
                            Price = 45.990000000000002,
                            Title = "Blazor WebAssembly: The Complete Guide"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Implement common design patterns in C# to improve code structure.",
                            Price = 50.0,
                            Title = "Design Patterns in C#"
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Đồ khô"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bánh truyền thống"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Đồ đặc sản"
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId1");

                    b.ToTable("Favorite", (string)null);
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BannerId")
                        .HasColumnType("int");

                    b.Property<int?>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("PathMedia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BannerId")
                        .IsUnique()
                        .HasFilter("[BannerId] IS NOT NULL");

                    b.HasIndex("BlogId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("ProductId");

                    b.ToTable("Media", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 51,
                            PathMedia = "https://example.com/avatar1.png",
                            Type = 1
                        },
                        new
                        {
                            Id = 52,
                            PathMedia = "https://example.com/avatar2.png",
                            Type = 1
                        },
                        new
                        {
                            Id = 53,
                            PathMedia = "https://example.com/avatar3.png",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            PathMedia = "chaca.png",
                            ProductId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            PathMedia = "tom-kho-gia-bao-nhieu-1kg.jpg",
                            ProductId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            PathMedia = "mamnhum.png",
                            ProductId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            PathMedia = "cach-lam-ca-kho-tam-gia-vi.jpg",
                            ProductId = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            PathMedia = "nem.png",
                            ProductId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            PathMedia = "banhit.png",
                            ProductId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            PathMedia = "mucrim.png",
                            ProductId = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            PathMedia = "chatre.png",
                            ProductId = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            PathMedia = "banhthuan.png",
                            ProductId = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            PathMedia = "ruoubauda.png",
                            ProductId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            PathMedia = "muc-ngao-ot-dac-san-binh-dinh-lam-qua.jpg",
                            ProductId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            PathMedia = "cach-lua-ca-chi-vang-kho-ngon.jpg",
                            ProductId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 33,
                            PathMedia = "Banh-trang-nuoc-dua-am-thuc-binh-dinh.jpg",
                            ProductId = 13,
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            PathMedia = "nuoc-mam-nhi-nguyen-chat-tam-quan-binh-dinh.jpg",
                            ProductId = 14,
                            Type = 1
                        },
                        new
                        {
                            Id = 35,
                            PathMedia = "các-món-từ-ruốc-khô.jpg",
                            ProductId = 15,
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            PathMedia = "cá-lao-khô-quy-nhơn.jpg",
                            ProductId = 16,
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            PathMedia = "banhhong.jpg",
                            ProductId = 17,
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            PathMedia = "banhtrangchaca.jpg",
                            ProductId = 18,
                            Type = 1
                        },
                        new
                        {
                            Id = 39,
                            PathMedia = "muc-ngao-ot-dac-san-binh-dinh-lam-qua.jpg",
                            ProductId = 19,
                            Type = 1
                        },
                        new
                        {
                            Id = 40,
                            PathMedia = "chả-ram-tôm-đất-quy-nhơn-ngon-loại-1.jpg",
                            ProductId = 20,
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            PathMedia = "ghe-sua-chien-gion.jpg",
                            ProductId = 21,
                            Type = 1
                        },
                        new
                        {
                            Id = 42,
                            PathMedia = "muc-mot-nang-gia-bao-nhieu-1kg.jpg",
                            ProductId = 22,
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            PathMedia = "cá-đù-một-nắng.jpg",
                            ProductId = 23,
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            PathMedia = "cha-bo-binh-dinh-nha-lam.jpg",
                            ProductId = 24,
                            Type = 1
                        },
                        new
                        {
                            Id = 45,
                            PathMedia = "banh-trang-nhung-binh-dinh.jpg",
                            ProductId = 25,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            BlogId = 1,
                            PathMedia = "mucrim.png",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            BlogId = 2,
                            PathMedia = "chatre.png",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            BlogId = 3,
                            PathMedia = "chaca.png",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 3,
                            PathMedia = "banh-xeo-my-cang-dac-san-binh-dinh.vntrip-e1501650332846.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            BlogId = 3,
                            PathMedia = "Banh-trang-nuoc-dua-am-thuc-binh-dinh.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            BlogId = 3,
                            PathMedia = "bat-bun-song-than.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            BlogId = 3,
                            PathMedia = "cua-huynh-de-vntrip-e1536313616403.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            BlogId = 3,
                            PathMedia = "goi-ca-chinh-binh-dinh.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            BlogId = 3,
                            PathMedia = "banhhong.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            BlogId = 3,
                            PathMedia = "banhtrangchaca.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 1,
                            BannerId = 1,
                            PathMedia = "slide_home_1.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            BannerId = 2,
                            PathMedia = "slide_home_2.jpg",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            BannerId = 3,
                            PathMedia = "slide_home_3.jpg",
                            Type = 1
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DayDelivery")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DayOrder")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeliveryState")
                        .HasColumnType("bit");

                    b.Property<bool>("PaidState")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId1");

                    b.ToTable("OrderDetail", (string)null);
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OffPrice")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mặc dù chả cá có thể là đặc sản và có mặt ở nhiều nơi nhưng không phải hương vị chả cá nào cũng như nhau. Sở dĩ chả cá Quy Nhơn là một trong các đặc sản Bình Định nổi tiếng vì vị ngon và lạ đặc trưng. Với nguyên liệu được tuyển chọn từ những con cá biển tươi ngon nhất và công thức chế biến độc quyền của người dân đã tạo nên sự khác biệt cho chả cá Quy Nhơn.\n Chả cá Quy Nhơn phổ biến có 2 loại là chả hấp và chả chiên. Ngoài việc thưởng thức thực tiếp miếng chả dai, giòn, thơm ngon đặc biệt, các bạn có thể dùng chả cá này để làm “topping” cho các món ăn khác như cơm, bún, phở. Đây cũng là một lựa chọn thích hợp để bạn mua về làm quà cho người thân và bạn bè nữa đó.",
                            Name = "Chả cá Quy Nhơn",
                            OffPrice = 10,
                            Price = 120000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tôm khô còn gọi là tôm nõn khô là một trong các loại thực phẩm giàu dinh dưỡng rất tốt cho sức khỏe. Chúng được làm từ tôm tươi tự nhiên và phơi khô dưới ánh nắng mặt trời hoặc sấy khô thủ công. 1kg tôm tươi làm được khoảng 2 lạng tôm khô, thành phẩm tôm có kích thước nhỏ hơn, có vị ngọt thanh đậm đà rất thơm.\nGiá trị dinh dưỡng của tôm vẫn giữ gần như nguyên vẹn, trong 100g tôm khô có: 347 kcal, 75,6g đạm, 235mg canxi, 4,6mg sắt, vitamin B1, B2, PP và 3,8g chất béo chưa bảo hòa.",
                            Name = "Tôm khô",
                            OffPrice = 20,
                            Price = 84000m,
                            Quality = 20,
                            Rating = 0
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhum có rất nhiều loại khác nhau, nhưng mắm nhum tại Bình Định đặc biệt được làm từ con nhum ta, tạo hương vị ngon đến nỗi “ăn với món gì cũng ngon”. Đồng thời mắm Nhum tại Mỹ An cũng từng là đặc sản Bình Định được tiến vua, và hiện nay là một món ăn mà du khách không thể bỏ lỡ khi đến Bình Định du lịch.\nNhum vốn là động vật với bê ngoài gai góc có thể làm đau người dân nếu đạp phải, và người dân nơi đây đã biến chúng thành một món ngon tuyệt vời. Mắm nhum còn có thể là món quà hảo hạng giúp bạn dùng làm quà tặng sau khi đến Bình Định du lịch, nếu được thì bạn nên đến Mỹ An để mua mắm nhum nhé.",
                            Name = "Mắm Nhum Mỹ An Bình Định",
                            OffPrice = 5,
                            Price = 20000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "cá cơm giàu vitamin A, nhiều axit béo, vitamin E, canxi, Vitamin A, giúp mắt sáng, ngăn ngừa các bệnh về mắt, duy trì làn da khỏe mạnh. Ăn cá cơm giúp giảm lượng cholesterol trong máu, ngăn ngừa các bệnh về tim mạch.\nCá cơm cung cấp một lượng lớn protein và đạm, nên chúng được sử dụng để làm nước mắm nhĩ",
                            Name = "Cá cơm khô",
                            OffPrice = 15,
                            Price = 18000m,
                            Quality = 55,
                            Rating = 0
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nem chua là một trong các đặc sản Bình Định được chế biến cầu kỳ và công phu. Với công thức hương vị đặc biệt để ướp những miếng thịt heo tươi ngon nhất và gói bên trong những lớp lá khế non và lớp lá chuối cầu kì, hương vị thơm ngon nổi tiếng của nem chợ huyện cũng từ đó mà vang xa.\nĐến Bình Định ngồi cắn một miếng nem và nhâm nhi một ít rượu Bàu Đá cũng đủ để bạn nhớ về hương vị ấy mỗi khi nhắc đến chuyến du lịch này đó. Ngoài ra, nem cũng là lựa chọn thích hợp để làm quà tặng, với hương vị tuyệt vời ấy ai lại lỡ không thích món quà mà bạn tặng.",
                            Name = "Nem chợ huyện",
                            OffPrice = 20,
                            Price = 150000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "“Muốn ăn bánh ít lá gai Lấy chồng Bình Định sợ dài đường đi\"Bánh ít lá gai là một trong các đặc sản Bình Định nổi tiếng. Để làm nên những chiếc bánh ít thơm ngon nức tiếng, người làm bánh phải lựa chọn và chuẩn bị những chiếc lá gai rất cầu kỳ vì đây là yếu tố quan trong quyết định đến hương vị của bánh. Kế đến là nếp và nhân cũng được lựa chọn và chế biến từ những nguyên liệu ngon nhất.\n Sau một quá trình xay bột, làm nhân, gói và hấp bánh, những chiếc bánh ít lá gai thơm ngon, dẻo dai với vị ngọt của nhân đậu xanh hoặc nhân dừa đã được ra lò. Với đặc sản này bạn nên thử ít nhất một lần, và đây cũng được xem là một món quà mà chắc chắn người thân của bạn sẽ thích.",
                            Name = "Bánh ít lá gai",
                            OffPrice = 10,
                            Price = 100000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mực rim là món ăn phổ biến khiến du thích yêu thích có mặt ở hầu hết những vùng biển lớn. Tuy nhiên mực rim hay còn gọi là mực ngào Bình Định có một hương vị thơm ngon rất riêng từ vùng biển duyên hải miền Trung. Mực rim Quy Nhơn được người dân làm từ những con mực tươi nhất và hương vị không nơi nào giống được.\n Với hương thơm ngon đặc biệt cùng vị cay cay kích thích vị giác, mực rim trở thành món ăn vặt siêu ngon và được mọi người vô cùng yêu thích. Đồng thời, với những hũ mực rim được làm sẵn giúp bạn có thể dễ dàng lựa chọn đặc sản Bình Định này để làm quà tặng.",
                            Name = "Mực rim Quy Nhơn",
                            OffPrice = 5,
                            Price = 150000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Với tên gọi độc và lạ của món Chả Tré, món đặc sản Bình Định này đã gợi nên sự tò mò với nhiều du khách muốn tìm hiểu và được thử món ăn độc đáo này. Mặc dù đã có mặt phổ biến khắp các tỉnh thành Trung Trung bộ, nhưng hương vị thơm ngon nhất vẫn là chả Tré Bình Định với cách làm và công thức chỉ vùng đất Bình Định mới làm nên được.\n Thành phần nguyên liệu làm chả Tré cũng tương tự với các loại nem, bì của miền bắc. Nhưng Tré Bình Định được người dân nơi đây khéo léo thay thế bằng nhiều loại nguyên liệu khác như tai heo, lỗ mũi heo, da heo, thịt ba chỉ,...Tré cũng thích hợp để trở thành món quà mang về khi bạn đến thăm Bình Định.",
                            Name = "Chả Tré rơm",
                            OffPrice = 20,
                            Price = 35000m,
                            Quality = 100,
                            Rating = 3
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nếu như Hà Nội có bánh cốm, Hải Dương có bánh đậu xanh, Vũng Tàu có bánh bông lan trứng muối,...và những loại bánh làm quà đặc trưng của nhiều tỉnh khác thì Quy Nhơn lại bánh thuẫn nổi tiếng để làm quà tặng cho người thân và bạn bè. Đây cũng là loại bánh phổ biến vào ngày Tết của người dân miền Trung.\n Bánh thuẫn có vị thơm ngon từ nguyên liệu như trứng gà, bột năng, bột bình tinh, đường, đâu ăn, vani và đặc biệt là khuôn đúc bánh. Quá trình đúc bánh bằng than đã góp phần tạo nên được mùi thơm đặc trưng của đặc sản Bình Định này.",
                            Name = "Bánh thuẫn",
                            OffPrice = 0,
                            Price = 15000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sở dĩ rượu Bàu đá được biết đến là một trong những đặc sản Bình Định nổi tiếng vì đây là loại rượu không nấu từ gạo thông thường như những loại rượu khác. Rượu Bàu đá Bình Định được nấu từ gạo lứt và chỉ khi sử dụng một nguồn nước trong một làng của tỉnh Bình Định mới đạt được hương vị ngon nhất.\n Từ xưa, rượu Bàu đá đã được tiến cung cho vua nên được xếp vào loại đặc sản thượng hạng của Bình Định. Rượu nổi tiếng dễ say vì có độ cồn rất cao, lên đến 50. Nhưng điều khiến người ta yêu thích hương vị của rượu là vị thanh mát mang lại cảm giác sảng khoái vô cùng. Đây cũng là một món quà thích hợp thể hiện sự kính trọng bạn có thể chọn.",
                            Name = "Rượu Bầu đá",
                            OffPrice = 0,
                            Price = 40000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Một trong những món ăn phải kể đến đầu tiên trong dah sách những món đặc sản Bình Định đó chính là mực ngào. Mực ngào có một hương vị thơm ngon rất riêng thu hút khách du lịch. Để chế biến được món mực ngào người đầu bếp đã phải rất công phu, tài tình tỉ mỉ chăm chút cho món ăn. Mực sau khi đươc thu mua từ những cảng hải sản tươi ngon được đem về sơ chế và chế biến luôn để giữ được độ tươi ngon nguyên vẹn  của mực.\nMực được  ướp cùng tiêu, tỏi, ớt, mắm và một số loại gia vị khác để tạo độ thơm ngon đặc trưng của mực. Món ăn này có vị cay đặc trưng, thơm thơm của các loại gia vị sẽ làm bạn thích thú và muốn ăn ngay từ cái nhìn đầu tiên. Gía của một cân mực ngào giao động từ  200.000 – 400.000 đồng.",
                            Name = "Mực ngào Bình Định",
                            OffPrice = 0,
                            Price = 250000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cá chỉ vàng là loài cá nước mặn (còn gọi là cá ngân chỉ) thức ăn của chúng là những sinh vật nổi. Thân cá dẹp hình thoi, hai bên có một sọc vàng chạy thẳng từ sau mắt đến gần vây đuôi, phần lưng màu xanh xám, bụng trắng bạc, trên mang cá có chấm đen, vây đuôi vàng, đầu cá hơi nhọn, miệng chếch, hàm dưới nhô ra.\n Cá chỉ vàng thịt trắng có vị ngọt thơm, giàu vitamin B, Omega 3 giúp ngăn ngừa bệnh tim mạch, tốt cho não bộ, cải thiện giấc ngủ...",
                            Name = "Khô cá chỉ vàng",
                            OffPrice = 0,
                            Price = 135000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khi đến du lịch Bình Định không thể không nhắc tới  món bánh tráng nước dừa. Đây là một món đặc sản nơi xứ dừa. Công đoạn chế biến bánh không quá cầu kì nhưng đòi hỏi sự tỉ mỉ, có kinh nghiệm của người tráng bánh. Nguyên liệu của bánh chủ yếu là Củ Mì ( củ sắn) được sắt nhỏ, xay lấy nước. Cơm dừa được nạo thành sợi nhỏ,  nước dừa và vừng đen. Tất cả đều được đổ chung vào một nồi lớn, trộn đều cho các gia vị hòa quyện cùng với nhau và được đun nóng. Bên cạnh đó có một chảo đang được đun nóng. Khi chảo nóng lên người tráng bánh sẽ dùng một cái gáo làm bằng sọ dừa có cán dài múc từng gáo nước bánh lên chảo và tráng đều. Tráng bánh phải đều tay để cơm dừa và vừng đen được dàn đều mặt bánh. Bánh phải tròn mỏng và không bị chỗ dày, chỗ mỏng thì mới là bánh đạt chuẩn. cứ tráng được mười chiếc  bánh thì đem ra phơi. khi ăn bạn cần nướng lên để bánh có độ phồng và dậy hết mùi thơm của vừng, của nước cốt dừa và cơm dừa. Có thể ăn bánh thay cơm ăn chỉ thấy no mà không thấy chán.",
                            Name = "Bánh tráng nước dừa",
                            OffPrice = 0,
                            Price = 120000m,
                            Quality = 50,
                            Rating = 0
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước mắm nhĩ hay nhỉ còn gọi là nước mắm kéo lù hoặc mắm cốt, là loại nước mắm được hứng từ các giọt nước mắm đầu tiên được “nhỉ” ra. Hay nói cách khác là rò rỉ ra từng giọt, từng giọt từ lỗ van đang đóng kín ở đáy của thùng hay lu vại đang muối cá đã đến thời gian chín có thể lấy nước mắm thành phẩm.",
                            Name = "Nước mắm nhĩ Bình Định",
                            OffPrice = 0,
                            Price = 95000m,
                            Quality = 50,
                            Rating = 0
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Con ruốc còn gọi là tép biển, tép moi, ở Việt Nam được coi là đặc sản. Chúng là động vật giáp xác 10 chân sống ở vùng nước mặn ven biển hay nước lợ. Ruốc dạng như tôm nhỏ, chỉ lớn khoảng 10–40 mm Do kích thước của con ruốc biển nhỏ, nên thường được dùng để làm nước mắm ruốc (là một loại mắm đặc sản của miền biển) hoặc phơi khô ruốc để chế biến thành các món ăn dân dã đậm đà hương vị biển.",
                            Name = "Ruốt khô",
                            OffPrice = 0,
                            Price = 200000m,
                            Quality = 50,
                            Rating = 0
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hải sản Quy Nhơn nổi tiếng khắp cả nước với nhiều loại hải sản phong phú đa dạng, trong đó Cá lao là một loại hải sản khô đặc biệt thơm ngon, chúng là một loại cá biển, sau khi được ngư dân đánh bắt được xẻ thịt, phơi khô tạo nên một loại thực phẩm thơm ngon đúng chất tinh túy từ biển.",
                            Name = "Cá Lao Khô Tẩm Gia Vị",
                            OffPrice = 0,
                            Price = 125000m,
                            Quality = 50,
                            Rating = 0
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh hồng Tam Quan là một trong những món đặc sản của Bình Định, được xem như biểu trưng cho tin vui, thường xuất hiện trong các dịp cưới hỏi của người dân nơi đây.\n Điều đặc biệt bánh hồng Tam Quan là bánh được làm từ gạo nếp Ngự nổi tiếng dẻo thơm. Do hoàn toàn không có chất bảo quản nên bánh chỉ để được 5 ngày thôi bạn nhé.",
                            Name = "Bánh hồng Tam Quan",
                            OffPrice = 0,
                            Price = 200000m,
                            Quality = 50,
                            Rating = 0
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh tráng chả cá là một trong những đặc sản nổi tiếng gần xa của Bình Định. Bánh tráng chả cá được làm từ nguyên liệu chính là cá cùng một ít gia vị và bột năng. Để món ăn đúng vị hơn bạn nên ăn kèm với rau răm nhé.",
                            Name = "Bánh tráng chả cá",
                            OffPrice = 0,
                            Price = 400000m,
                            Quality = 50,
                            Rating = 0
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nếu đã đến với đất Bình Định thì bạn nhất định phải thử qua món mực ngào vị tỏi nhé. Món ăn là sự hòa quyện giữa vị mực vừa tươi vừa giòn cùng vị cay đặc trưng của ớt và tỏi. Bạn nhớ bảo quản món này ở nhiệt độ thoáng mát nha.",
                            Name = "Mực ngào vị tỏi",
                            OffPrice = 0,
                            Price = 200000m,
                            Quality = 100,
                            Rating = 0
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chả ram tôm đất là một trong những món ngon đặc sản nổi tiếng của miền đất võ Bình Định, món ăn này phù hợp với mọi lứa tuổi, từ già đến trẻ đều yêu thích và thường xuyên xuất hiện trong các bữa cơm gia đình.\n Miếng chả ram tôm đất Bình Định giòn tan của lớp bánh tráng chiên bên ngoài, bên trong có thịt tôm ngọt tự nhiên, một chút ngầy ngậy của thịt mỡ, tất cả tạo nên hương vị đặc biệt hấp dẫn, gây nghiện cho thực khách khi dùng thử món ăn độc đáo này.",
                            Name = "Chả ram tôm đất",
                            OffPrice = 0,
                            Price = 890000m,
                            Quality = 45,
                            Rating = 0
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ghẹ sữa là ghẹ còn non có kích thước nhỏ, cỡ ngón chân cái người lớn, nhiều nhất vào tháng 5 đến tháng 11, thời điểm ghẹ sinh sản nhiều.\nGhẹ sữa có hàm lượng dinh dưỡng cao, nhiều canxi, đạm, sắt, các vitamin A, B1, B2, C và đặc biệt là magnesium, calcium và axit béo omega 3, có lợi cho sức khỏe và rất tốt cho người có vấn đề tim mạch và hỗ trợ tăng trưởng chiều cao cho trẻ.",
                            Name = "Ghẹ sữa rim tỏi ớt, rang me, chiên giòn",
                            OffPrice = 15,
                            Price = 90000m,
                            Quality = 44,
                            Rating = 4
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mực một nắng là loại hải sản đặc biệt, để làm mực 1 nắng được ngon, sau khi xẻ phải rửa mực tươi bằng nước biển, rồi phơi dưới trời nắng gắt. Chỉ được phơi qua một nắng để mực vẫn giữ được độ tươi ngon, bên ngoài ráo nước, bên trong dẻo và giòn. \nNhững vùng biển có nước biển càng mặn thì mực 1 nắng sẽ càng ngon, đặc biệt là các khu vực miền Trung. Mực một nắng có nhiều loại, nhưng mực ngon nhất vẫn là làm từ những con mực ống và mực lá.\nĐây là một trong các đặc sản nổi tiếng của Bình Định được du khách tìm mua làm quà.",
                            Name = "Mực một nắng",
                            OffPrice = 20,
                            Price = 500000m,
                            Quality = 50,
                            Rating = 2
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cá đù hay Cá lù đù là một họ cá thuộc bộ Cá vược (Perciformes) có kích thước lớn, chúng sống ở vùng biển nhiệt đới, cận nhiệt đới. Tại vùng biển Việt Nam, có khoảng 270 loài trong 70 chi, đáng kể nhất là cá lù đù bạc chiếm số lượng lớn trong 20 loài như cá lù đù măng đen, cá lù đù lỗ tai đen, cá lù đù kẽm, cá lù đù sóc, cá lù đù đỏ dạ...\nChúng sống thành từng đàn lớn ở gần bờ, thường núp trong những rạn, hốc đá. Thức ăn của chúng là các loại động vật thủy sinh, côn trùng hay cá nhỏ, giáp xác.\n Vì muốn dự trữ được lâu nên sau khi được đánh bắt, ngư dân chọn cá tươi làm sạch, xẻ lóc bỏ xương, bỏ đầu để ráo. Sau đó, đem phơi khô dưới 1 nắng gắt để cá se lại để thịt dẻo dẻo. Hoặc có thể phơi cho thật khô để dự trữ ăn dần.\n Cá đù 1 nắng phần thân sau của cá có nhiều mỡ, rất béo. Loại cá này có vị ngọt dịu deo dẻo và đặc biệt thịt mềm, hậu bùi, có thể chế biến thành nhiều món ngon hấp dẫn. \nHiện nay, đây là đặc sản được rất nhiều người săn lùng, kể cả người nước ngoài cũng rất thích thú với vị ngon ngọt của nó “đặc biệt là giá cả phải chăng”.",
                            Name = "Cá đù một nắng",
                            OffPrice = 0,
                            Price = 16000m,
                            Quality = 12,
                            Rating = 0
                        },
                        new
                        {
                            Id = 24,
                            DateCreated = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chả Bò (Giò Bò) Bình Định Chính Gốc – Cây 500G",
                            Name = "Chả Bò (Giò Bò) Bình Định Chính Gốc – Cây 500G",
                            OffPrice = 0,
                            Price = 180000m,
                            Quality = 15,
                            Rating = 0
                        },
                        new
                        {
                            Id = 25,
                            DateCreated = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đến với Bình Định, du khách sẽ được thưởng thức những món được làm từ các loại bánh tráng. Nào là bánh tráng mè nướng, bánh tráng nước cốt dừa Tam Quan hay bánh tráng bột mì nhứt nướng, bánh tráng gạo nhúng, … loại bánh nào cũng ngon nhứt nách. Hôm nay, Đặc Sản Bình Định Online xin được giới thiệu đến quý khách một loại bánh tráng độc đáo hơn cả đó là bánh tráng nhúng giòn Phù Mỹ. Hãy cùng khám phá bạn nhé. Nếu có cơ hội đến Bình Định hãy thử một lần thưởng thức loại bánh tráng đặc sản Phù Mỹ để tự cảm nhận hương vị thơm ngon đặc trưng của nó nhé.",
                            Name = "Bánh Tráng Nhúng Giòn Phù Mỹ",
                            OffPrice = 0,
                            Price = 45000m,
                            Quality = 20,
                            Rating = 0
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 1
                        });
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "ProviderKey", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.UserRoles", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.RoleIdentity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", "Customer")
                        .WithMany("Favorites")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinhDinhFood.Domain.Entities.Product", null)
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinhDinhFood.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Media", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Banner", "Banner")
                        .WithOne("Image")
                        .HasForeignKey("BinhDinhFood.Domain.Entities.Media", "BannerId");

                    b.HasOne("BinhDinhFood.Domain.Entities.Blog", "Blog")
                        .WithMany("Images")
                        .HasForeignKey("BlogId");

                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", "Customer")
                        .WithOne("Image")
                        .HasForeignKey("BinhDinhFood.Domain.Entities.Media", "CustomerId");

                    b.HasOne("BinhDinhFood.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId");

                    b.Navigation("Banner");

                    b.Navigation("Blog");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Order", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinhDinhFood.Domain.Entities.Product", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BinhDinhFood.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinhDinhFood.Domain.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Review", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BinhDinhFood.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.RoleIdentity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.ApplicationUser", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Auth.RoleIdentity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Banner", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Blog", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BinhDinhFood.Domain.Entities.Product", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductCategories");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
